# Changes here will be overwritten by Copier
_commit: v0.3.14
_src_path: https://github.com/fohte/generic-boilerplate
description: ''
is_public: false
node_package_manager: pnpm
project_name: renovate-config
type: node
use_release_please: false

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated

#copier updated
