name: Validate renovate config

on:
  push:
    paths:
      - .github/workflows/validate.yml
      - '*.json5'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - run: |
          npx --package renovate -c 'renovate-config-validator *.json5 --strict'
