name: Validate renovate config

on:
  push:
    paths:
      - .github/workflows/validate.yml
      - '*.json5'

  # every 5:00 AM Saturday (JST)
  schedule:
    - cron: '0 20 * * 5'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npx --package renovate -c 'renovate-config-validator *.json5 --strict'
